name: Deploy Website
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: npm install
      - name: Deploy app
        run: |
          git config --global user.email ${{secrets.GH_EMAIL}}
          git config --global user.name ${{secrets.GH_USERNAME}}
          git remote set-url origin https://${{secrets.GH_PAT}}@github.com/${{secrets.GH_USERNAME}}/personal-website.git
          CI=false npm run deploy -- -m "Deploy website to GitHub Pages"
